CREATE USER IF NOT EXISTS 'sa'@'%' IDENTIFIED BY 'Select*From123';

CREATE DATABASE IF NOT EXISTS teste;

ALTER DATABASE teste
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON teste.* TO 'sa'@'%' IDENTIFIED BY 'Select*From123';